### ISSUE TITLE
Decompressor for Gzip using FPGA？

### ISSUE THREAD

**Issue by TomHuangsrc** [WangXuan95/FPGA-Gzip-compressor#3]
do you have the respond decompressor for gzip using fpga? it can decompress the output of your code. Thanks.

**Comment by WangXuan95** [comment]
I dont have FPGA-based decompressor, but you can try anothor open-sourced project [HDL-deflate](https://github.com/tomtor/HDL-deflate) . It includes FPGA-based compressor and decompressor. Although its compressor performance is not as good as mine, its decompressor seems support complete GZIP spec.
